name: OK to test enable actions

on:
  pull_request:
    types: [labeled]
    branches: [ 'main', 'master', 'release-*' ]

jobs:
  check-ok-to-test:
    name: Check ok-to-test label
    runs-on: ubuntu-latest
    steps:
    - name: Check ok-to-test label
      shell: bash
      run: |
        set -x
        echo runs url = '${{ github.event.repository.url }}/actions/runs?branch=${{ github.event.head.ref }}&status=action_required&event=pull_request'
        echo '${{ github.head.sha }}'
        echo '${{ github.ref }}'
        echo '${{ github.api_url }}'
        echo '${{ github.event.label.name }}'
        echo '${{ toJSON(github.event) }}'
        echo '${{ toJSON(github) }}'
