name: OK to test enable actions

on:
  pull_request:
    types: [labeled]
    branches: [ 'main', 'master', 'release-*' ]

jobs:
  check-ok-to-test:
    name: Check ok-to-test label
    runs-on: ubuntu-latest
    steps:
    - name: Curl runs to approve
      shell: bash
      run: |
        set -x
        RUNS_URL='${{ github.event.repository.url }}/actions/runs?branch=${{ github.event.pull_request.head.ref }}&status=action_required&event=pull_request'
        echo 'branch_actions_response<<EOF' >> $GITHUB_ENV
        curl "$RUNS_URL" >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo head sha '${{ github.event.pull_request.head.sha }}'
        echo '${{ github.ref }}'
        echo '${{ github.event.label.name }}'
        #echo '${{ toJSON(github.event) }}'
        #echo '${{ toJSON(github) }}'
    - name: Process runs payload
      shell: bash
      run: |
        set -x
        echo actions response = '${{ fromJSON(env.branch_actions_response).workflow_runs.*.head_sha }}'
